# Generated by Django 3.1.4 on 2021-01-09 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=12, unique=True)),
                ('additional_phone', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=64, null=True)),
                ('additional_email', models.BooleanField(default=False)),
                ('print_same', models.BooleanField(default=True)),
                ('print_name', models.CharField(max_length=100)),
                ('invoice_static', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(blank=True, choices=[('', ''), ('nc', 'NC'), ('sc', 'SC'), ('va', 'VA')], default='', max_length=2, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.TextField(blank=True, max_length=254, null=True)),
                ('notes_popup', models.BooleanField(default=False)),
                ('is_exempt', models.BooleanField(default=False)),
                ('exemption_number', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('current_balance', models.IntegerField(default=0)),
                ('has_credit', models.BooleanField(default=False)),
                ('credit_limit', models.IntegerField(blank=True, null=True)),
                ('credit_terms', models.CharField(blank=True, choices=[('', ''), ('30', 'Net 30'), ('60', 'Net 60')], default='', max_length=2, null=True)),
                ('opening_balance', models.IntegerField(blank=True, null=True)),
                ('opening_balance_date', models.DateField(blank=True, null=True)),
                ('has_attachments', models.BooleanField(default=False)),
                ('is_inactive', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12, unique=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.wholesalecustomer')),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.wholesalecustomer')),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
    ]
