# Generated by Django 3.1.4 on 2021-03-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesalecustomer',
            name='state',
            field=models.CharField(blank=True, choices=[('', ''), ('NC', 'NC'), ('SC', 'SC'), ('VA', 'VA'), ('KY', 'KY')], default='NC', max_length=2, null=True),
        ),
    ]
