# Generated by Django 3.1.4 on 2021-01-25 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WCAdditionalEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=64, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.wholesalecustomer')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
