# Generated by Django 3.1.4 on 2021-01-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesalecustomer',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='wholesalecustomer',
            name='email2',
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='wholesalecustomer',
            name='email3',
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='wholesalecustomer',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='wholesalecustomer',
            name='phone_number3',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='wholesalecustomer',
            name='state',
            field=models.CharField(blank=True, choices=[('', ''), ('NC', 'NC'), ('SC', 'SC'), ('VA', 'VA'), ('KY', 'KY')], default='', max_length=2, null=True),
        ),
    ]
