# Generated by Django 3.1.4 on 2021-01-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_wcadditionalphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesalecustomer',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='wholesalecustomer',
            name='email3',
        ),
        migrations.RemoveField(
            model_name='wholesalecustomer',
            name='phone_number2',
        ),
        migrations.RemoveField(
            model_name='wholesalecustomer',
            name='phone_number3',
        ),
    ]
