# Generated by Django 3.1.4 on 2021-01-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210108_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesalecustomer',
            name='phone_number_type',
            field=models.CharField(choices=[('m', 'Mobile'), ('o', 'Office')], default='m', max_length=1),
        ),
    ]
