# Generated by Django 3.1.4 on 2021-01-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210126_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wcadditionalphone',
            name='name',
        ),
        migrations.AddField(
            model_name='wholesalecustomer',
            name='email2',
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='wholesalecustomer',
            name='email3',
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='wholesalecustomer',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='wholesalecustomer',
            name='phone_number3',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.DeleteModel(
            name='WCAdditionalEmail',
        ),
        migrations.DeleteModel(
            name='WCAdditionalPhone',
        ),
    ]
