# Generated by Django 3.1.4 on 2021-01-09 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_wholesalecustomer_phone_number_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesalecustomer',
            name='phone_number_type',
        ),
    ]
