# Generated by Django 3.1.4 on 2021-01-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_additionalphone_phone_number_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalphone',
            name='phone_number_type',
        ),
        migrations.RemoveField(
            model_name='wholesalecustomer',
            name='phone_number_type',
        ),
    ]
