# Generated by Django 3.1.4 on 2021-01-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20210111_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesalecustomer',
            name='current_balance',
        ),
    ]
