# Generated by Django 3.1.4 on 2021-01-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_remove_wholesalecustomer_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalphone',
            name='phone_number_type',
            field=models.CharField(choices=[('m', 'Mobile'), ('o', 'Office')], default='o', max_length=1),
        ),
        migrations.AddField(
            model_name='wholesalecustomer',
            name='current_balance',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='wholesalecustomer',
            name='phone_number_type',
            field=models.CharField(choices=[('m', 'Mobile'), ('o', 'Office')], default='m', max_length=1),
        ),
    ]
