# Generated by Django 3.1.4 on 2021-01-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_auto_20210116_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalphone',
            name='phone_number_type',
            field=models.CharField(blank=True, choices=[('m', 'Mobile'), ('o', 'Office')], default='o', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='wholesalecustomer',
            name='phone_number_type',
            field=models.CharField(blank=True, choices=[('m', 'Mobile'), ('o', 'Office')], default='m', max_length=1, null=True),
        ),
    ]
