# Generated by Django 3.1.4 on 2021-01-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_auto_20210116_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalphone',
            name='phone_number_type',
        ),
        migrations.RemoveField(
            model_name='wholesalecustomer',
            name='phone_number_type',
        ),
        migrations.AlterField(
            model_name='wholesalecustomer',
            name='credit_terms',
            field=models.CharField(blank=True, choices=[('', ''), ('Net 30', 'Net 30'), ('Net 60', 'Net 60')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wholesalecustomer',
            name='state',
            field=models.CharField(blank=True, choices=[('', ''), ('NC', 'NC'), ('SC', 'SC'), ('VA', 'VA')], default='', max_length=2, null=True),
        ),
    ]
