# Generated by Django 3.1.4 on 2021-01-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_auto_20210119_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalphone',
            name='company_name',
        ),
        migrations.AddField(
            model_name='wholesalecustomer',
            name='additional_email2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wholesalecustomer',
            name='additional_email3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wholesalecustomer',
            name='additional_phone2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wholesalecustomer',
            name='additional_phone3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wholesalecustomer',
            name='email2',
            field=models.EmailField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wholesalecustomer',
            name='email3',
            field=models.EmailField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wholesalecustomer',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wholesalecustomer',
            name='phone_number3',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wholesalecustomer',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='AdditionalEmail',
        ),
        migrations.DeleteModel(
            name='AdditionalPhone',
        ),
    ]
