# Generated by Django 3.1.4 on 2021-01-19 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_auto_20210119_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesalecustomer',
            name='additional_email3',
        ),
        migrations.RemoveField(
            model_name='wholesalecustomer',
            name='additional_phone3',
        ),
    ]
