# Generated by Django 3.1.4 on 2021-02-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('', ''), ('Farm', 'Farm'), ('Pavers', 'Pavers'), ('Compost', 'Compost'), ('Other', 'Other')], default='', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
