# Generated by Django 3.1.4 on 2021-01-29 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('transfer_type', models.CharField(choices=[('', ''), ('Delivery', 'Delivery'), ('Pickup', 'Pickup'), ('TBD', 'TBD')], default='', max_length=8)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('transfer_time', models.CharField(choices=[('', ''), ('AM', 'AM'), ('PM', 'PM'), ('Anytime', 'Anytime'), ('8am-10am', '8am-10am'), ('10am-12pm', '10am-12pm'), ('12pm-2pm', '12pm-2pm'), ('2pm-4pm', '2pm-4pm'), ('First Drop', 'First Drop')], default='', max_length=20)),
                ('status_order', models.BooleanField(default=True)),
                ('status_confirmed', models.BooleanField(default=False)),
                ('status_inventory_assignment', models.BooleanField(default=False)),
                ('status_invoice_made', models.BooleanField(default=False)),
                ('status_out_for_delivery', models.BooleanField(default=False)),
                ('status_delivered', models.BooleanField(default=False)),
                ('status_invoice_paid', models.BooleanField(default=False)),
                ('status_completed', models.BooleanField(default=False)),
                ('entered_on', models.DateField()),
                ('last_modified_on', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.wholesalecustomer')),
                ('entered_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
