# Generated by Django 3.1.4 on 2021-03-23 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_load_number', models.CharField(max_length=12)),
                ('inv_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cut_date', models.DateField(blank=True, null=True)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('transfer_type', models.CharField(choices=[('', ''), ('Delivery', 'Delivery'), ('Pickup', 'Pickup'), ('TBD', 'TBD')], default='', max_length=8)),
                ('transfer_time', models.CharField(choices=[('', ''), ('Overnight', 'Overnight'), ('Morning', 'Morning'), ('Noon', 'Noon'), ('8am-10am', '8am-10am'), ('10am-12pm', '10am-12pm'), ('12pm-2pm', '12pm-2pm'), ('2pm-4pm', '2pm-4pm')], default='', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['temp_load_number'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('', ''), ('Delivery', 'Delivery'), ('Pickup', 'Pickup'), ('TBD', 'TBD')], default='', max_length=8)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('transfer_time', models.CharField(choices=[('', ''), ('AM', 'AM'), ('PM', 'PM'), ('Anytime', 'Anytime'), ('8am-10am', '8am-10am'), ('10am-12pm', '10am-12pm'), ('12pm-2pm', '12pm-2pm'), ('2pm-4pm', '2pm-4pm'), ('First Drop', 'First Drop'), ('Installing Tomorrow', 'Installing Tomorrow')], default='', max_length=20)),
                ('is_delivery', models.BooleanField(default=False)),
                ('delivery_street', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_city', models.CharField(blank=True, max_length=64, null=True)),
                ('delivery_state', models.CharField(blank=True, choices=[('', ''), ('NC', 'NC'), ('SC', 'SC'), ('VA', 'VA'), ('KY', 'KY')], default='NC', max_length=2, null=True)),
                ('delivery_zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('order_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('print_notes', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Order', 'Order'), ('Confirmed', 'Confirmed'), ('Load Matched', 'Load Matched'), ('Invoice Made', 'Invoice Made'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Settled', 'Settled'), ('Completed', 'Completed')], default='Order', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.wholesalecustomer')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='LoadItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.load')),
            ],
        ),
    ]
