# Generated by Django 3.1.4 on 2021-03-23 03:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='farm',
            field=models.ForeignKey(limit_choices_to={'category': 'Farm'}, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
        ),
        migrations.AlterField(
            model_name='load',
            name='transfer_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='load',
            name='transfer_time',
            field=models.CharField(choices=[('', ''), ('Overnight', 'Overnight'), ('Morning', 'Morning'), ('Noon', 'Noon'), ('8am-10am', '8am-10am'), ('10am-12pm', '10am-12pm'), ('12pm-2pm', '12pm-2pm'), ('2pm-4pm', '2pm-4pm')], default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='loaditem',
            name='item',
            field=models.ForeignKey(limit_choices_to={'category': 'Sod'}, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
