# Generated by Django 3.1.4 on 2021-01-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='number',
            new_name='order_number',
        ),
    ]
