# Generated by Django 3.1.4 on 2021-02-01 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210130_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='order_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='entered_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='entered_on',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_modified_on',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status_completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status_confirmed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status_inventory_assignment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status_invoice_made',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status_invoice_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status_out_for_delivery',
        ),
    ]
