# Generated by Django 3.1.4 on 2021-03-28 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210322_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='cut_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='load',
            name='temp_load_number',
            field=models.CharField(max_length=20),
        ),
    ]
