# Generated by Django 3.1.4 on 2021-03-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210327_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='temp_load_number',
            field=models.CharField(max_length=12),
        ),
    ]
