# Generated by Django 3.1.4 on 2021-08-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210327_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaditem',
            name='available',
            field=models.IntegerField(null=True),
        ),
    ]
