# Generated by Django 3.1.4 on 2021-03-05 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210301_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='order',
            new_name='which_order',
        ),
    ]
