# Generated by Django 3.1.4 on 2021-03-05 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210304_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='which_order',
            new_name='order',
        ),
    ]
