# Generated by Django 3.1.4 on 2021-08-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_loaditem_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='temp_load_number',
            field=models.CharField(max_length=30),
        ),
    ]
