# Generated by Django 3.1.4 on 2021-08-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210815_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaditem',
            name='available',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
