# Generated by Django 3.1.4 on 2021-08-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_loaditem_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaditem',
            name='available',
            field=models.IntegerField(null=True),
        ),
    ]
