# Generated by Django 3.1.4 on 2021-08-16 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210815_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaditem',
            name='available',
        ),
    ]
