# Generated by Django 3.1.4 on 2021-08-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_loaditem_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaditem',
            name='available',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
